[project]
name = "250904-test-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "espeak-phonemizer>=1.3.1",
    "numpy>=2.3.2",
    "onnxruntime>=1.22.1",
    "pyopenjtalk>=0.4.1",
    "soundfile>=0.13.1",
]
